//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forecast.Domain.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int ForecastID { get; set; }
        public int CityID { get; set; }
        public int Period { get; set; }
        public int Temperature { get; set; }
        public int Symbol { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime NextUpdate { get; set; }
    
        public virtual City City { get; set; }
    }
}
